### ISSUE TITLE
project progress and beta release

### ISSUE THREAD

**Issue by dab** [sennah911/WinMan#3]
Hello here, found information about your project. Any updates?

**Comment by sennah911** [comment]
Unfortunately real work has gotten in the way, and I have for the moment no time to finish it. However this issue just opened my eyes, and I realise I should give something to the people waiting. For everyone that has expressed an interest on twitter to test the app, I will send a "working" binary in the following days, and a sample config file for you to mess around with. Then _maybe_ later, when real life is not in the way as much I will clean up the code and open source it.

**Comment by dab** [comment]
That's great. Thank you. Will wait for testing.
